const host = 'https://api.wardenger.me/admin/'
// const host = 'http://192.168.0.104:3000/admin/'

export const login = `${host}session`
export const newUser = `${host}users/new`
export const userAction = `${host}users`
export const uploadImg = `${host}news/uploadimg`
export const newMessage = `${host}news/new`
export const messageAll = `${host}news/all`
export const messageOne = `${host}news/one`
export const messageEdit = `${host}news/update`
export const messageDel = `${host}news/delete`
export const troubleAction = `${host}bugs`
export const troubleKindAdd = `${host}bugs/categorys/new`
export const troubleKindTop = `${host}bugs/categorys/top`
export const troubleKindAction = `${host}bugs/categorys`
export const workOrderAction = `${host}orders`
export const machineUploadImg = `${host}devices/uploadimg`
export const newMachine = `${host}devices/new`
export const machineAction = `${host}devices`
export const authorityNew = `${host}auths/new`
export const authorityAction = `${host}auths`
export const authorityPut = `${host}auth/change`
export const authEdit = `${host}auths/one`
